# shellcheck shell=bash

export CLICKUP_TOKEN=""
export CLICKUP_BASE_URL=""

# clickup/inbox_open.sh
export CLICKUP_INBOX_ID=""
export CLICKUP_INBOX_PATH=""

# clickup/roadmaps_open.sh
export CLICKUP_PORTFOLIO_ROADMAP_PATH=""
export CLICKUP_PROGRAM_INCREMENT_ROADMAP_PATH=""
export CLICKUP_PROGRAM_INCREMENT_PLAN_PATH=""

# clickup/backlog_open.sh — path
export CLICKUP_BACKLOG_CRM_PATH=""
export CLICKUP_BACKLOG_PIM_PATH=""
export CLICKUP_BACKLOG_LEGACY_PATH=""
export CLICKUP_BACKLOG_TMS_PATH=""
export CLICKUP_BACKLOG_KIOSK_PATH=""
export CLICKUP_BACKLOG_BI_PATH=""
export CLICKUP_BACKLOG_DEMAND_PATH=""
export CLICKUP_BACKLOG_DRP_PATH=""
export CLICKUP_BACKLOG_SHOP_PATH=""
export CLICKUP_BACKLOG_SHOP_ADMIN_PATH=""
export CLICKUP_BACKLOG_AFTERSALES_PATH=""
export CLICKUP_BACKLOG_POM_PATH=""

# discord/bot.js
export DISCORD_BOT_TOKEN=""
export DISCORD_MEETING_GUILD_ID=""
export DISCORD_MEETING_VOICE_CHANNEL_ID=""