# shellcheck shell=bash

export CLICKUP_TOKEN=""
export CLICKUP_BASE_URL=""
export CLICKUP_INBOX_ID=""
export CLICKUP_INBOX_PATH=""
export CLICKUP_PORTFOLIO_ROADMAP_PATH=""
export CLICKUP_PROGRAM_INCREMENT_ROADMAP_PATH=""
export CLICKUP_PROGRAM_INCREMENT_PLAN_PATH=""